version: "3.7"

services:
  backend:
    build: './backend'
    restart: always
    volumes: 
      - ./backend/:/home/app
    ports:
      - '8000:8000'
    networks:
      - backnet

  nginx:
    build: './nginx'
    restart: always
    ports: 
      - '80:80'

    volumes:
      - ./frontend/:/home/app/frontend
      - ./game/:/home/app/game
      - ./windows:/home/app/windows/
      - ./android:/home/app/android/

    depends_on:
      - backend
    
    networks:
      - backnet

    # volumes:
    #   - ./nginx/conf.d/:/etc/nginx/conf.d/
    #   - ./game/:/home/app/game
    #   - ./frontend/:/home/app/frontend


networks:
  backnet: